{% set version = '0.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-greta
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/greta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/greta/greta_{{ version }}.tar.gz
  sha256: 3b585f0bf1f73f7da7e87b1f07cb663a5dbded0c8e73ea33e2294b3d0a00499f

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-r6
    - r-abind
    - r-callr
    - r-cli >=3.0.0
    - r-coda
    - r-future >=1.22.1
    - r-glue >=1.5.1
    - r-parallelly >=1.29.0
    - r-progress >=1.2.0
    - r-reticulate >=1.19.0
    - r-tensorflow >=2.7.0
    - r-yesno

  run:
    - r-base
    - r-r6
    - r-abind
    - r-callr
    - r-cli >=3.0.0
    - r-coda
    - r-future >=1.22.1
    - r-glue >=1.5.1
    - r-parallelly >=1.29.0
    - r-progress >=1.2.0
    - r-reticulate >=1.19.0
    - r-tensorflow >=2.7.0
    - r-yesno

test:
  commands:
    - $R -e "library('greta')"           # [not win]
    - "\"%R%\" -e \"library('greta')\""  # [win]

about:
  home: https://greta-stats.org
  dev_url: https://github.com/greta-dev/greta
  license: Apache-2.0
  summary: "Write statistical models in R and fit them by MCMC and optimisation on CPUs and GPUs,
    using Google 'TensorFlow'.  greta lets you write your own model like in BUGS, JAGS
    and Stan, except that you write models right in R, it scales well to massive datasets,
    and it\u2019s easy to extend and build on.  See the website for more information,
    including tutorials, examples, package documentation, and the greta forum."
  license_family: Apache
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Type: Package
# Package: greta
# Title: Simple and Scalable Statistical Modelling in R
# Version: 0.4.3
# Authors@R: c( person("Nick", "Golding", , "nick.golding.research@gmail.com", role = "aut", comment = c(ORCID = "0000-0001-8916-5570")), person("Nicholas", "Tierney", , "nicholas.tierney@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "https://orcid.org/0000-0003-1460-8722")), person("Simon", "Dirmeier", role = "ctb"), person("Adam", "Fleischhacker", role = "ctb"), person("Shirin", "Glander", role = "ctb"), person("Martin", "Ingram", role = "ctb"), person("Lee", "Hazel", role = "ctb"), person("Lionel", "Hertzog", role = "ctb"), person("Tiphaine", "Martin", role = "ctb"), person("Matt", "Mulvahill", role = "ctb"), person("Michael", "Quinn", role = "ctb"), person("David", "Smith", role = "ctb"), person("Paul", "Teetor", role = "ctb"), person("Jian", "Yen", role = "ctb") )
# Description: Write statistical models in R and fit them by MCMC and optimisation on CPUs and GPUs, using Google 'TensorFlow'.  greta lets you write your own model like in BUGS, JAGS and Stan, except that you write models right in R, it scales well to massive datasets, and its easy to extend and build on.  See the website for more information, including tutorials, examples, package documentation, and the greta forum.
# License: Apache License 2.0
# URL: https://greta-stats.org
# BugReports: https://github.com/greta-dev/greta/issues
# Depends: R (>= 3.1.0)
# Imports: abind, callr, cli (>= 3.0.0), coda, future (>= 1.22.1), glue (>= 1.5.1), methods, parallelly (>= 1.29.0), progress (>= 1.2.0), R6, reticulate (>= 1.19.0), tensorflow (>= 2.7.0), yesno
# Suggests: bayesplot, covr, cramer, DiagrammeR, extraDistr, fields, ggplot2, knitr, lattice, MASS, MCMCpack, mockery, mvtnorm, rmarkdown, rmutil, spelling, testthat (>= 3.1.0), tidyverse, truncdist, withr
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-GB
# RoxygenNote: 7.2.0
# SystemRequirements: Python (>= 2.7.0) with header files and shared library; TensorFlow (v1.14; https://www.tensorflow.org/); TensorFlow Probability (v0.7.0; https://www.tensorflow.org/probability/)
# Collate: 'package.R' 'utils.R' 'greta_mcmc_list.R' 'tf_functions.R' 'overloaded.R' 'node_class.R' 'node_types.R' 'variable.R' 'probability_distributions.R' 'mixture.R' 'joint.R' 'unknowns_class.R' 'greta_array_class.R' 'as_data.R' 'distribution.R' 'operators.R' 'functions.R' 'transforms.R' 'structures.R' 'extract_replace_combine.R' 'dag_class.R' 'greta_model_class.R' 'progress_bar.R' 'inference_class.R' 'samplers.R' 'optimisers.R' 'inference.R' 'install_tensorflow.R' 'calculate.R' 'callbacks.R' 'simulate.R' 'chol2symm.R' 'install_greta_deps.R' 'conda_greta_env.R' 'greta_stash.R' 'greta_create_conda_env.R' 'greta_install_miniconda.R' 'greta_install_python_deps.R' 'new_install_process.R' 'reinstallers.R' 'checkers.R' 'test_if_forked_cluster.R' 'testthat-helpers.R' 'zzz.R' 'internals.R'
# NeedsCompilation: no
# Packaged: 2022-09-08 13:42:15 UTC; njtierney
# Author: Nick Golding [aut] (<https://orcid.org/0000-0001-8916-5570>), Nicholas Tierney [aut, cre] (<https://orcid.org/0000-0003-1460-8722>), Simon Dirmeier [ctb], Adam Fleischhacker [ctb], Shirin Glander [ctb], Martin Ingram [ctb], Lee Hazel [ctb], Lionel Hertzog [ctb], Tiphaine Martin [ctb], Matt Mulvahill [ctb], Michael Quinn [ctb], David Smith [ctb], Paul Teetor [ctb], Jian Yen [ctb]
# Maintainer: Nicholas Tierney <nicholas.tierney@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-09-08 14:12:56 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
